export const lore: Shelf = {
  name: "<sprite name=colours.liminal> Lore",
  category: "lore",
  id: "kat.lore",
  rows: 8,
  columns: 9,
  areas: [
    {
      expression: "[fragmentsecrethistories]",
      background: "hawthorn.lore_secrethistories_shelf",
      x: 1,
      y: 2,
    },
    {
      expression: "[fragmentsecrethistoriesb]",
      background: "hawthorn.lore_secrethistories_shelf",
      x: 1,
      y: 3,
    },
    {
      expression: "[fragmentsecrethistoriesc]",
      background: "hawthorn.lore_secrethistories_shelf",
      x: 1,
      y: 4,
    },
    {
      expression: "[fragmentsecrethistoriesd]",
      background: "hawthorn.lore_secrethistories_shelf",
      x: 1,
      y: 5,
    },
    {
      expression: "[fragmentsecrethistoriese]",
      background: "hawthorn.lore_secrethistories_shelf",
      x: 1,
      y: 6,
    },
    {
      expression: "[fragmentsecrethistoriesf]",
      background: "hawthorn.lore_secrethistories_shelf",
      x: 1,
      y: 7,
    },
    {
      expression: "[fragmentsecrethistoriesg]",
      background: "hawthorn.lore_secrethistories_shelf",
      x: 1,
      y: 8,
    },

    {
      expression: "[fragmentknock]",
      background: "hawthorn.lore_knock_shelf",
      x: 2,
      y: 2,
    },
    {
      expression: "[fragmentknockb]",
      background: "hawthorn.lore_knock_shelf",
      x: 2,
      y: 3,
    },
    {
      expression: "[fragmentknockc]",
      background: "hawthorn.lore_knock_shelf",
      x: 2,
      y: 4,
    },
    {
      expression: "[fragmentknockd]",
      background: "hawthorn.lore_knock_shelf",
      x: 2,
      y: 5,
    },
    {
      expression: "[fragmentknocke]",
      background: "hawthorn.lore_knock_shelf",
      x: 2,
      y: 6,
    },
    {
      expression: "[fragmentknockf]",
      background: "hawthorn.lore_knock_shelf",
      x: 2,
      y: 7,
    },
    {
      expression: "[fragmentknockg]",
      background: "hawthorn.lore_knock_shelf",
      x: 2,
      y: 8,
    },
    {
      expression: "[fragmentlantern]",
      background: "hawthorn.lore_lantern_shelf",
      x: 3,
      y: 2,
    },
    {
      expression: "[fragmentlanternb]",
      background: "hawthorn.lore_lantern_shelf",
      x: 3,
      y: 3,
    },
    {
      expression: "[fragmentlanternc]",
      background: "hawthorn.lore_lantern_shelf",
      x: 3,
      y: 4,
    },
    {
      expression: "[fragmentlanternd]",
      background: "hawthorn.lore_lantern_shelf",
      x: 3,
      y: 5,
    },
    {
      expression: "[fragmentlanterne]",
      background: "hawthorn.lore_lantern_shelf",
      x: 3,
      y: 6,
    },
    {
      expression: "[fragmentlanternf]",
      background: "hawthorn.lore_lantern_shelf",
      x: 3,
      y: 7,
    },
    {
      expression: "[fragmentlanterng]",
      background: "hawthorn.lore_lantern_shelf",
      x: 3,
      y: 8,
    },

    {
      expression: "[fragmentforge]",
      background: "hawthorn.lore_forge_shelf",
      x: 4,
      y: 2,
    },
    {
      expression: "[fragmentforgeb]",
      background: "hawthorn.lore_forge_shelf",
      x: 4,
      y: 3,
    },
    {
      expression: "[fragmentforgec]",
      background: "hawthorn.lore_forge_shelf",
      x: 4,
      y: 4,
    },
    {
      expression: "[fragmentforged]",
      background: "hawthorn.lore_forge_shelf",
      x: 4,
      y: 5,
    },
    {
      expression: "[fragmentforgee]",
      background: "hawthorn.lore_forge_shelf",
      x: 4,
      y: 6,
    },
    {
      expression: "[fragmentforgef]",
      background: "hawthorn.lore_forge_shelf",
      x: 4,
      y: 7,
    },
    {
      expression: "[fragmentforgeg]",
      background: "hawthorn.lore_forge_shelf",
      x: 4,
      y: 8,
    },
    {
      expression: "[fragmentedge]",
      background: "hawthorn.lore_edge_shelf",
      x: 5,
      y: 2,
    },
    {
      expression: "[fragmentedgeb]",
      background: "hawthorn.lore_edge_shelf",
      x: 5,
      y: 3,
    },
    {
      expression: "[fragmentedgec]",
      background: "hawthorn.lore_edge_shelf",
      x: 5,
      y: 4,
    },
    {
      expression: "[fragmentedged]",
      background: "hawthorn.lore_edge_shelf",
      x: 5,
      y: 5,
    },
    {
      expression: "[fragmentedgee]",
      background: "hawthorn.lore_edge_shelf",
      x: 5,
      y: 6,
    },
    {
      expression: "[fragmentedgef]",
      background: "hawthorn.lore_edge_shelf",
      x: 5,
      y: 7,
    },
    {
      expression: "[fragmentedgeg]",
      background: "hawthorn.lore_edge_shelf",
      x: 5,
      y: 8,
    },

    {
      expression: "[fragmentwinter]",
      background: "hawthorn.lore_winter_shelf",
      x: 6,
      y: 2,
    },
    {
      expression: "[fragmentwinterb]",
      background: "hawthorn.lore_winter_shelf",
      x: 6,
      y: 3,
    },
    {
      expression: "[fragmentwinterc]",
      background: "hawthorn.lore_winter_shelf",
      x: 6,
      y: 4,
    },
    {
      expression: "[fragmentwinterd]",
      background: "hawthorn.lore_winter_shelf",
      x: 6,
      y: 5,
    },
    {
      expression: "[fragmentwintere]",
      background: "hawthorn.lore_winter_shelf",
      x: 6,
      y: 6,
    },
    {
      expression: "[fragmentwinterf]",
      background: "hawthorn.lore_winter_shelf",
      x: 6,
      y: 7,
    },
    {
      expression: "[fragmentwinterg]",
      background: "hawthorn.lore_winter_shelf",
      x: 6,
      y: 8,
    },

    {
      expression: "[fragmentheart]",
      background: "hawthorn.lore_heart_shelf",
      x: 7,
      y: 2,
    },
    {
      expression: "[fragmentheartb]",
      background: "hawthorn.lore_heart_shelf",
      x: 7,
      y: 3,
    },
    {
      expression: "[fragmentheartc]",
      background: "hawthorn.lore_heart_shelf",
      x: 7,
      y: 4,
    },
    {
      expression: "[fragmentheartd]",
      background: "hawthorn.lore_heart_shelf",
      x: 7,
      y: 5,
    },
    {
      expression: "[fragmenthearte]",
      background: "hawthorn.lore_heart_shelf",
      x: 7,
      y: 6,
    },
    {
      expression: "[fragmentheartf]",
      background: "hawthorn.lore_heart_shelf",
      x: 7,
      y: 7,
    },
    {
      expression: "[fragmentheartg]",
      background: "hawthorn.lore_heart_shelf",
      x: 7,
      y: 8,
    },

    {
      expression: "[fragmentgrail]",
      background: "hawthorn.lore_grail_shelf",
      x: 8,
      y: 2,
    },
    {
      expression: "[fragmentgrailb]",
      background: "hawthorn.lore_grail_shelf",
      x: 8,
      y: 3,
    },
    {
      expression: "[fragmentgrailc]",
      background: "hawthorn.lore_grail_shelf",
      x: 8,
      y: 4,
    },
    {
      expression: "[fragmentgraild]",
      background: "hawthorn.lore_grail_shelf",
      x: 8,
      y: 5,
    },
    {
      expression: "[fragmentgraile]",
      background: "hawthorn.lore_grail_shelf",
      x: 8,
      y: 6,
    },
    {
      expression: "[fragmentgrailf]",
      background: "hawthorn.lore_grail_shelf",
      x: 8,
      y: 7,
    },
    {
      expression: "[fragmentgrailg]",
      background: "hawthorn.lore_grail_shelf",
      x: 8,
      y: 8,
    },
    {
      expression: "[fragmentmoth]",
      background: "hawthorn.lore_moth_shelf",
      x: 9,
      y: 2,
    },
    {
      expression: "[fragmentmothb]",
      background: "hawthorn.lore_moth_shelf",
      x: 9,
      y: 3,
    },
    {
      expression: "[fragmentmothc]",
      background: "hawthorn.lore_moth_shelf",
      x: 9,
      y: 4,
    },
    {
      expression: "[fragmentmothd]",
      background: "hawthorn.lore_moth_shelf",
      x: 9,
      y: 5,
    },
    {
      expression: "[fragmentmothe]",
      background: "hawthorn.lore_moth_shelf",
      x: 9,
      y: 6,
    },
    {
      expression: "[fragmentmothf]",
      background: "hawthorn.lore_moth_shelf",
      x: 9,
      y: 7,
    },
    {
      expression: "[fragmentmothg]",
      background: "hawthorn.lore_moth_shelf",
      x: 9,
      y: 8,
    },
    {
      id: "paintingmastersecrethistories",
      expression: "[paintingmastersecrethistories]",
      background: "hawthorn.painting_shelf",
      x: 1,
      y: 1,
    },
    {
      id: "paintingmasterknock",
      expression: "[paintingmasterknock]",
      background: "hawthorn.painting_shelf",
      x: 2,
      y: 1,
    },
    {
      id: "paintingmasterlantern",
      expression: "[paintingmasterlantern]",
      background: "hawthorn.painting_shelf",
      x: 3,
      y: 1,
    },
    {
      id: "paintingmasterforge",
      expression: "[paintingmasterforge]",
      background: "hawthorn.painting_shelf",
      x: 4,
      y: 1,
    },
    {
      id: "paintingmasteredge",
      expression: "[paintingmasteredge]",
      background: "hawthorn.painting_shelf",
      x: 5,
      y: 1,
    },
    {
      id: "paintingmasterwinter",
      expression: "[paintingmasterwinter]",
      background: "hawthorn.painting_shelf",
      x: 6,
      y: 1,
    },
    {
      id: "paintingmasterheart",
      expression: "[paintingmasterheart]",
      background: "hawthorn.painting_shelf",
      x: 7,
      y: 1,
    },
    {
      id: "paintingmastergrail",
      expression: "[paintingmastergrail]",
      background: "hawthorn.painting_shelf",
      x: 8,
      y: 1,
    },
    {
      id: "paintingmastermoth",
      expression: "[paintingmastermoth]",
      background: "hawthorn.painting_shelf",
      x: 9,
      y: 1,
    },
  ],
};
export const loreNoSH: Shelf = {
  name: "<sprite name=colours.liminal> Lore (No Secret Histories)",
  category: "lore",
  id: "kat.lore.compat",
  rows: 8,
  columns: 8,
  areas: [
    {
      expression: "[fragmentknock]",
      background: "hawthorn.lore_knock_shelf",
      x: 1,
      y: 2,
    },
    {
      expression: "[fragmentknockb]",
      background: "hawthorn.lore_knock_shelf",
      x: 1,
      y: 3,
    },
    {
      expression: "[fragmentknockc]",
      background: "hawthorn.lore_knock_shelf",
      x: 1,
      y: 4,
    },
    {
      expression: "[fragmentknockd]",
      background: "hawthorn.lore_knock_shelf",
      x: 1,
      y: 5,
    },
    {
      expression: "[fragmentknocke]",
      background: "hawthorn.lore_knock_shelf",
      x: 1,
      y: 6,
    },
    {
      expression: "[fragmentknockf]",
      background: "hawthorn.lore_knock_shelf",
      x: 1,
      y: 7,
    },
    {
      expression: "[fragmentknockg]",
      background: "hawthorn.lore_knock_shelf",
      x: 1,
      y: 8,
    },
    {
      expression: "[fragmentlantern]",
      background: "hawthorn.lore_lantern_shelf",
      x: 2,
      y: 2,
    },
    {
      expression: "[fragmentlanternb]",
      background: "hawthorn.lore_lantern_shelf",
      x: 2,
      y: 3,
    },
    {
      expression: "[fragmentlanternc]",
      background: "hawthorn.lore_lantern_shelf",
      x: 2,
      y: 4,
    },
    {
      expression: "[fragmentlanternd]",
      background: "hawthorn.lore_lantern_shelf",
      x: 2,
      y: 5,
    },
    {
      expression: "[fragmentlanterne]",
      background: "hawthorn.lore_lantern_shelf",
      x: 2,
      y: 6,
    },
    {
      expression: "[fragmentlanternf]",
      background: "hawthorn.lore_lantern_shelf",
      x: 2,
      y: 7,
    },
    {
      expression: "[fragmentlanterng]",
      background: "hawthorn.lore_lantern_shelf",
      x: 2,
      y: 8,
    },

    {
      expression: "[fragmentforge]",
      background: "hawthorn.lore_forge_shelf",
      x: 3,
      y: 2,
    },
    {
      expression: "[fragmentforgeb]",
      background: "hawthorn.lore_forge_shelf",
      x: 3,
      y: 3,
    },
    {
      expression: "[fragmentforgec]",
      background: "hawthorn.lore_forge_shelf",
      x: 3,
      y: 4,
    },
    {
      expression: "[fragmentforged]",
      background: "hawthorn.lore_forge_shelf",
      x: 3,
      y: 5,
    },
    {
      expression: "[fragmentforgee]",
      background: "hawthorn.lore_forge_shelf",
      x: 3,
      y: 6,
    },
    {
      expression: "[fragmentforgef]",
      background: "hawthorn.lore_forge_shelf",
      x: 3,
      y: 7,
    },
    {
      expression: "[fragmentforgeg]",
      background: "hawthorn.lore_forge_shelf",
      x: 3,
      y: 8,
    },
    {
      expression: "[fragmentedge]",
      background: "hawthorn.lore_edge_shelf",
      x: 4,
      y: 2,
    },
    {
      expression: "[fragmentedgeb]",
      background: "hawthorn.lore_edge_shelf",
      x: 4,
      y: 3,
    },
    {
      expression: "[fragmentedgec]",
      background: "hawthorn.lore_edge_shelf",
      x: 4,
      y: 4,
    },
    {
      expression: "[fragmentedged]",
      background: "hawthorn.lore_edge_shelf",
      x: 4,
      y: 5,
    },
    {
      expression: "[fragmentedgee]",
      background: "hawthorn.lore_edge_shelf",
      x: 4,
      y: 6,
    },
    {
      expression: "[fragmentedgef]",
      background: "hawthorn.lore_edge_shelf",
      x: 4,
      y: 7,
    },
    {
      expression: "[fragmentedgeg]",
      background: "hawthorn.lore_edge_shelf",
      x: 4,
      y: 8,
    },

    {
      expression: "[fragmentwinter]",
      background: "hawthorn.lore_winter_shelf",
      x: 5,
      y: 2,
    },
    {
      expression: "[fragmentwinterb]",
      background: "hawthorn.lore_winter_shelf",
      x: 5,
      y: 3,
    },
    {
      expression: "[fragmentwinterc]",
      background: "hawthorn.lore_winter_shelf",
      x: 5,
      y: 4,
    },
    {
      expression: "[fragmentwinterd]",
      background: "hawthorn.lore_winter_shelf",
      x: 5,
      y: 5,
    },
    {
      expression: "[fragmentwintere]",
      background: "hawthorn.lore_winter_shelf",
      x: 5,
      y: 6,
    },
    {
      expression: "[fragmentwinterf]",
      background: "hawthorn.lore_winter_shelf",
      x: 5,
      y: 7,
    },
    {
      expression: "[fragmentwinterg]",
      background: "hawthorn.lore_winter_shelf",
      x: 5,
      y: 8,
    },

    {
      expression: "[fragmentheart]",
      background: "hawthorn.lore_heart_shelf",
      x: 6,
      y: 2,
    },
    {
      expression: "[fragmentheartb]",
      background: "hawthorn.lore_heart_shelf",
      x: 6,
      y: 3,
    },
    {
      expression: "[fragmentheartc]",
      background: "hawthorn.lore_heart_shelf",
      x: 6,
      y: 4,
    },
    {
      expression: "[fragmentheartd]",
      background: "hawthorn.lore_heart_shelf",
      x: 6,
      y: 5,
    },
    {
      expression: "[fragmenthearte]",
      background: "hawthorn.lore_heart_shelf",
      x: 6,
      y: 6,
    },
    {
      expression: "[fragmentheartf]",
      background: "hawthorn.lore_heart_shelf",
      x: 6,
      y: 7,
    },
    {
      expression: "[fragmentheartg]",
      background: "hawthorn.lore_heart_shelf",
      x: 6,
      y: 8,
    },

    {
      expression: "[fragmentgrail]",
      background: "hawthorn.lore_grail_shelf",
      x: 7,
      y: 2,
    },
    {
      expression: "[fragmentgrailb]",
      background: "hawthorn.lore_grail_shelf",
      x: 7,
      y: 3,
    },
    {
      expression: "[fragmentgrailc]",
      background: "hawthorn.lore_grail_shelf",
      x: 7,
      y: 4,
    },
    {
      expression: "[fragmentgraild]",
      background: "hawthorn.lore_grail_shelf",
      x: 7,
      y: 5,
    },
    {
      expression: "[fragmentgraile]",
      background: "hawthorn.lore_grail_shelf",
      x: 7,
      y: 6,
    },
    {
      expression: "[fragmentgrailf]",
      background: "hawthorn.lore_grail_shelf",
      x: 7,
      y: 7,
    },
    {
      expression: "[fragmentgrailg]",
      background: "hawthorn.lore_grail_shelf",
      x: 7,
      y: 8,
    },
    {
      expression: "[fragmentmoth]",
      background: "hawthorn.lore_moth_shelf",
      x: 8,
      y: 2,
    },
    {
      expression: "[fragmentmothb]",
      background: "hawthorn.lore_moth_shelf",
      x: 8,
      y: 3,
    },
    {
      expression: "[fragmentmothc]",
      background: "hawthorn.lore_moth_shelf",
      x: 8,
      y: 4,
    },
    {
      expression: "[fragmentmothd]",
      background: "hawthorn.lore_moth_shelf",
      x: 8,
      y: 5,
    },
    {
      expression: "[fragmentmothe]",
      background: "hawthorn.lore_moth_shelf",
      x: 8,
      y: 6,
    },
    {
      expression: "[fragmentmothf]",
      background: "hawthorn.lore_moth_shelf",
      x: 8,
      y: 7,
    },
    {
      expression: "[fragmentmothg]",
      background: "hawthorn.lore_moth_shelf",
      x: 8,
      y: 8,
    },
    {
      id: "paintingmastersecrethistories",
      expression: "[paintingmastersecrethistories]",
      background: "hawthorn.painting_shelf",
      x: 1,
      y: 1,
    },
    {
      id: "paintingmasterknock",
      expression: "[paintingmasterknock]",
      background: "hawthorn.painting_shelf",
      x: 1,
      y: 1,
    },
    {
      id: "paintingmasterlantern",
      expression: "[paintingmasterlantern]",
      background: "hawthorn.painting_shelf",
      x: 2,
      y: 1,
    },
    {
      id: "paintingmasterforge",
      expression: "[paintingmasterforge]",
      background: "hawthorn.painting_shelf",
      x: 3,
      y: 1,
    },
    {
      id: "paintingmasteredge",
      expression: "[paintingmasteredge]",
      background: "hawthorn.painting_shelf",
      x: 4,
      y: 1,
    },
    {
      id: "paintingmasterwinter",
      expression: "[paintingmasterwinter]",
      background: "hawthorn.painting_shelf",
      x: 5,
      y: 1,
    },
    {
      id: "paintingmasterheart",
      expression: "[paintingmasterheart]",
      background: "hawthorn.painting_shelf",
      x: 6,
      y: 1,
    },
    {
      id: "paintingmastergrail",
      expression: "[paintingmastergrail]",
      background: "hawthorn.painting_shelf",
      x: 7,
      y: 1,
    },
    {
      id: "paintingmastermoth",
      expression: "[paintingmastermoth]",
      background: "hawthorn.painting_shelf",
      x: 8,
      y: 1,
    },
  ],
};
